
name: houston-quickstart

stages:
  - name: start
    downstream:
      - upload-file-customers
      - upload-file-sales
    params:
      topic: houston-cloud-function-topic-kit-fagan
      operation: none

  - name: upload-file-customers
    downstream:
      - run-query-clean-customers
    params:
      topic: houston-cloud-function-topic-kit-fagan
      file_location: customers.csv
      operation: upload

  - name: upload-file-sales
    downstream:
      - run-query-clean-sales
    params:
      topic: houston-cloud-function-topic-kit-fagan
      file_location: sales.csv
      operation: upload

  - name: run-query-clean-customers
    params:
      topic: houston-cloud-function-topic-kit-fagan
      operation: query
      query_name: foo.sql

  - name: run-query-clean-sales
    params:
      topic: houston-cloud-function-topic-kit-fagan
      operation: query
      query_name: foo.sql

  - name: run-query-report
    params:
      topic: houston-cloud-function-topic-kit-fagan
      operation: query
      query_name: foo.sql
    upstream:
      - run-query-clean-customers
      - run-query-clean-sales
