name: houston-quickstart

services:
  - name: houston-quickstart
    trigger:
      method: pubsub
      topic: houston-cloud-function-topic

stages:
  - name: start
    service: houston-quickstart
    downstream:
      - upload-file-customers
      - upload-file-sales
    params:
      operation: none

  - name: upload-file-customers
    service: houston-quickstart
    downstream:
      - run-query-clean-customers
    params:
      file_location: customers.csv
      operation: upload

  - name: upload-file-sales
    service: houston-quickstart
    downstream:
      - run-query-clean-sales
    params:
      file_location: sales.csv
      operation: upload

  - name: run-query-clean-customers
    service: houston-quickstart
    params:
      operation: query
      query_name: foo.sql

  - name: run-query-clean-sales
    service: houston-quickstart
    params:
      operation: query
      query_name: foo.sql

  - name: run-query-report
    service: houston-quickstart
    params:
      operation: query
      query_name: foo.sql
    upstream:
      - run-query-clean-customers
      - run-query-clean-sales
